import { BookOpen } from 'lucide-react';
import FormulaCard from '../components/FormulaCard';

function SectionLabel({ children }: { children: string }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16, marginTop: 32 }}>
      <div style={{ width: 2, height: 12, background: '#e8a020' }} />
      <span style={{ fontFamily: 'var(--font-data)', fontSize: 9, letterSpacing: '0.18em', color: '#e8a020', textTransform: 'uppercase' }}>
        {children}
      </span>
      <div style={{ flex: 1, height: 1, background: 'var(--border-dim)' }} />
    </div>
  );
}

export default function MethodologyPage() {
  return (
    <div style={{ maxWidth: 1100, margin: '0 auto', padding: '28px 24px' }}>

      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
          <BookOpen size={13} style={{ color: '#e8a020' }} />
          <span style={{ fontFamily: 'var(--font-data)', fontSize: 9, letterSpacing: '0.2em', color: '#e8a020' }}>
            ENGINEERING DOCUMENTATION
          </span>
        </div>
        <h1 style={{ fontFamily: 'var(--font-data)', fontSize: 22, fontWeight: 700, color: '#e2eaf5', margin: 0 }}>
          ENGINEERING BASIS
        </h1>
        <p style={{ fontSize: 12, color: '#374561', marginTop: 4, maxWidth: 600 }}>
          All health scores, reliability values, and recommendations are derived from explicit engineering formulas.
          This page documents the complete mathematical basis.
        </p>
      </div>

      {/* Disclaimer */}
      <div style={{
        border: '1px solid rgba(250,204,21,0.2)',
        background: 'rgba(250,204,21,0.04)',
        padding: '12px 16px',
        marginBottom: 8,
        fontFamily: 'var(--font-data)', fontSize: 10,
        letterSpacing: '0.06em', color: '#6b7fa3', lineHeight: 1.7,
      }}>
        ⚠ DISCLAIMER: This system uses simulated data. Not certified for real aircraft maintenance,
        flight safety, or operational aviation decision-making.
        Compliant with: educational portfolio use only.
      </div>

      <SectionLabel>Project Objective</SectionLabel>
      <p style={{ fontSize: 12, color: '#6b7fa3', lineHeight: 1.8, maxWidth: 720 }}>
        SkyPulse AI demonstrates how aerospace reliability engineering principles can be applied to
        aircraft Condition-Based Maintenance (CBM). The system estimates subsystem health from simulated
        sensor data, calculates Remaining Useful Life (RUL), prioritizes maintenance using FMEA-style
        risk scoring, and presents actionable recommendations.
      </p>

      <SectionLabel>Assumptions</SectionLabel>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
        {[
          'All sensor data is generated by a stochastic simulation -- not from a real aircraft.',
          'Exponential reliability model (constant failure rate) is used as a first-order approximation. Real components follow Weibull distributions.',
          'Subsystem health scores are weighted linear combinations of normalized sensor scores.',
          'Rated component lives are representative MRO literature values, not type-certified figures.',
          'Stress factors are simplified multipliers; physics-of-failure models would be required for certified PHM.',
          'All sensor thresholds (nominal / warning / critical) are approximate and for demonstration only.',
          'MTBF estimates carry large uncertainty at low failure counts.',
        ].map((item, i) => (
          <div key={i} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
            <span style={{ fontFamily: 'var(--font-data)', fontSize: 9, color: '#374561', flexShrink: 0, marginTop: 2 }}>
              {String(i + 1).padStart(2, '0')}
            </span>
            <span style={{ fontSize: 12, color: '#6b7fa3', lineHeight: 1.6 }}>{item}</span>
          </div>
        ))}
      </div>

      <SectionLabel>Sensor Parameters</SectionLabel>
      <div className="panel" style={{ overflow: 'hidden' }}>
        <div style={{
          display: 'grid', gridTemplateColumns: '2fr 1fr 1fr 1fr 1fr',
          padding: '8px 18px',
          borderBottom: '1px solid var(--border-dim)',
          fontFamily: 'var(--font-data)', fontSize: 8, letterSpacing: '0.14em',
          color: '#374561', textTransform: 'uppercase',
        }}>
          {['Sensor', 'Unit', 'Nominal', 'Warning', 'Critical'].map(h => <span key={h}>{h}</span>)}
        </div>
        {[
          ['Engine Temperature', 'C', '650', '750', '850'],
          ['Engine Vibration', 'mm/s RMS', '2.0', '5.0', '10.0'],
          ['Oil Pressure', 'PSI', '60', '45', '30'],
          ['Fuel Flow', 'kg/hr', '850', '950', '1100'],
          ['Hydraulic Pressure', 'PSI', '3000', '2400', '1800'],
          ['Battery Voltage', 'V', '28.0', '25.5', '23.0'],
          ['Generator Voltage', 'V AC', '115', '112', '108'],
          ['Avionics Temperature', 'C', '45', '60', '75'],
        ].map((row, i, arr) => (
          <div
            key={row[0]}
            style={{
              display: 'grid', gridTemplateColumns: '2fr 1fr 1fr 1fr 1fr',
              padding: '9px 18px',
              borderBottom: i < arr.length - 1 ? '1px solid var(--border-dim)' : 'none',
            }}
          >
            <span style={{ fontSize: 12, color: '#94a3b8' }}>{row[0]}</span>
            {row.slice(1).map((cell, j) => (
              <span key={j} style={{
                fontFamily: 'var(--font-data)', fontSize: 11,
                color: j === 0 ? '#22c55e' : j === 1 ? '#facc15' : '#f43f5e',
              }}>{cell}</span>
            ))}
          </div>
        ))}
      </div>

      <SectionLabel>Calculation Formulas</SectionLabel>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
        <FormulaCard
          title="Engine Health Score"
          formula={`H_engine = 0.30·T + 0.30·V + 0.20·P + 0.20·U`}
          description="Weighted sum of normalized sensor scores. Each sensor linearly interpolated between nominal (100) and critical (0)."
          variables={[
            { symbol: 'T', meaning: 'Temperature score (0-100)' },
            { symbol: 'V', meaning: 'Vibration score (0-100)' },
            { symbol: 'P', meaning: 'Oil pressure score (0-100)' },
            { symbol: 'U', meaning: 'Usage / age score (0-100)' },
          ]}
        />
        <FormulaCard
          title="Remaining Useful Life"
          formula={`Eff_Age = FH × SF\nRUL    = Rated_Life − Eff_Age\nSF     = ((1+0.5(1−T_n)) + (1+0.8(1−V_n))) / 2`}
          description="Effective age accounts for degraded conditions accelerating wear beyond calendar aging."
          variables={[
            { symbol: 'FH', meaning: 'Flight hours' },
            { symbol: 'SF', meaning: 'Stress factor (> 1 = accelerated aging)' },
            { symbol: 'T_n', meaning: 'Temperature score normalised 0-1' },
          ]}
        />
        <FormulaCard
          title="Reliability Function"
          formula={`R(t) = e^(−λt)\nλ    = 1 / MTBF\nMTBF = Operating_Hours / Failures`}
          description="Exponential model assumes constant failure rate. Probability of surviving mission time t."
          variables={[
            { symbol: 'λ', meaning: 'Failure rate (per flight hour)' },
            { symbol: 't', meaning: 'Mission time (app uses 100-hr mission)' },
          ]}
        />
        <FormulaCard
          title="Vibration Severity Index"
          formula={`VSI = V_measured / V_nominal\nV_nominal = 2.0 mm/s RMS`}
          description="Per ISO 10816. VSI > 2.5 triggers warning; VSI > 4.0 is critical range."
        />
        <FormulaCard
          title="FMEA Risk Priority Number"
          formula={`RPN = S × P × D\n\nLow:      RPN < 100\nMedium:   100 ≤ RPN < 300\nHigh:     300 ≤ RPN < 600\nCritical: RPN ≥ 600`}
          description="FMEA-derived risk score. Each factor 1-10. Severity from subsystem criticality; Probability from health degradation."
          variables={[
            { symbol: 'S', meaning: 'Severity 1-10 (engine=9, landing gear=8)' },
            { symbol: 'P', meaning: 'Probability from health score degradation' },
            { symbol: 'D', meaning: 'Detectability (lower = easier to detect)' },
          ]}
        />
        <FormulaCard
          title="Fatigue Consumed"
          formula={`Fatigue_% = (Actual_Cycles / Rated_Cycles) × 100`}
          description="Proportion of structural fatigue life consumed. Mandatory inspection triggered at 80% in most maintenance manuals."
        />
      </div>

      <SectionLabel>Risk Categories</SectionLabel>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 8 }}>
        {[
          { level: 'LOW', color: '#22c55e', health: '80 - 100%', rpn: 'RPN < 100' },
          { level: 'MEDIUM', color: '#facc15', health: '60 - 79%', rpn: 'RPN 100-299' },
          { level: 'HIGH', color: '#fb923c', health: '40 - 59%', rpn: 'RPN 300-599' },
          { level: 'CRITICAL', color: '#f43f5e', health: 'Below 40%', rpn: 'RPN ≥ 600' },
        ].map(r => (
          <div key={r.level} className="panel" style={{ padding: '14px 16px', overflow: 'hidden', position: 'relative' }}>
            <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 1, background: `linear-gradient(90deg, ${r.color}, transparent)` }} />
            <div style={{ fontFamily: 'var(--font-data)', fontSize: 11, fontWeight: 700, color: r.color, letterSpacing: '0.1em', marginBottom: 6 }}>
              {r.level}
            </div>
            <div style={{ fontFamily: 'var(--font-data)', fontSize: 9, color: '#4a5a7a', marginBottom: 2 }}>HEALTH: {r.health}</div>
            <div style={{ fontFamily: 'var(--font-data)', fontSize: 9, color: '#374561' }}>{r.rpn}</div>
          </div>
        ))}
      </div>

      <SectionLabel>Limitations</SectionLabel>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
        {[
          'No real sensor data -- all values generated by the telemetry simulator.',
          'Linear health scoring does not capture nonlinear degradation dynamics.',
          'No machine learning; predictions are rule-based threshold logic.',
          'Single-sensor-to-subsystem mapping; real PHM uses multi-sensor fusion.',
          'No environmental factors (altitude, load, humidity) in the degradation model.',
          'MTBF estimates use very small failure counts; wide confidence intervals implied.',
        ].map((item, i) => (
          <div key={i} style={{ display: 'flex', gap: 8 }}>
            <span style={{ fontFamily: 'var(--font-data)', color: '#f43f5e', fontSize: 10, flexShrink: 0 }}>×</span>
            <span style={{ fontSize: 12, color: '#4a5a7a', lineHeight: 1.6 }}>{item}</span>
          </div>
        ))}
      </div>

      <SectionLabel>Future Improvements</SectionLabel>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
        {[
          'Weibull degradation model with particle filter RUL estimation.',
          'LSTM or Transformer-based anomaly detection on raw telemetry sequences.',
          'Bayesian MTBF updating as failure events arrive in real time.',
          'ADS-B data integration for actual flight hours and cycle tracking.',
          'Maintenance scheduling optimizer using reliability-centered logic.',
          'Export in iSpec 2200 / MIL-STD-1388 report format.',
        ].map((item, i) => (
          <div key={i} style={{ display: 'flex', gap: 8 }}>
            <span style={{ fontFamily: 'var(--font-data)', color: '#22c55e', fontSize: 10, flexShrink: 0 }}>+</span>
            <span style={{ fontSize: 12, color: '#4a5a7a', lineHeight: 1.6 }}>{item}</span>
          </div>
        ))}
      </div>

    </div>
  );
}
